### ISSUE TITLE
Invalid properties in properties.schema

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt-contrib-languagePicker#10]
Possibly a copy and paste error, but there appears to be a few accessibility properties that don't really belong in the Language Picker extension here:
https://github.com/adaptlearning/adapt-contrib-languagePicker/blob/master/properties.schema#L130-L186

**Comment by moloko** [comment]
no I think this is correct - it's annoying duplication but necessary due to course.json not having been loaded by the time the languagePicker is displayed

We probably need to have a think about redoing the json load order... or maybe moving this sort of thing to a separate file like labels.json or strings.json

**Comment by brian-learningpool** [comment]
That makes sense -- thanks for clarifying.  I guess if those particular strings lived in config.json it wouldn't be a problem?

**Comment by moloko** [comment]
that would solve for languagePicker text but wouldn't help for other things e.g. https://github.com/adaptlearning/adapt_framework/issues/1238

**Comment by moloko** [comment]
There is an error in the properties.schema however - on line 69 the 'default' is set to `"en"` but this is not one of the allowed values, it should be `"ltr"`

**Comment by lc-thomasberger** [comment]
@moloko fixed
